FROM mcr.microsoft.com/playwright/python:v1.40.0
WORKDIR /app
COPY requirements.txt extract.py .
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m playwright install --with-deps chromium firefox webkit
CMD ["python", "extract.py"]